FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install system deps (IMPORTANT)
RUN apt-get update && apt-get install -y \
    postgresql-client \
    netcat-openbsd \
    curl

COPY . .

RUN chmod +x /app/docker/start-api.sh

CMD ["bash", "/app/docker/start-api.sh"]